# -*- Mode: makefile -*-
#
# SuperH specific tweaks
#

.SUFFIXES:

BINARIES = \
	test_MOVI.bin \
	test_MOVWI.bin \
	test_MOVLI.bin \
	test_MOV.bin \
	test_MOVBS.bin \
	test_MOVWS.bin \
	test_MOVLS.bin \
	test_MOVBL.bin \
	test_MOVWL.bin \
	test_MOVLL.bin \
	test_MOVBM.bin \
	test_MOVWM.bin \
	test_MOVLM.bin \
	test_MOVBP.bin \
	test_MOVWP.bin \
	test_MOVLP.bin \
	test_MOVBS0.bin \
	test_MOVWS0.bin \
	test_MOVLS0.bin \
	test_MOVBL0.bin \
	test_MOVWL0.bin \
	test_MOVLL0.bin \
	test_LDCGBR.bin \
	test_MOVBLG.bin \
	test_MOVWLG.bin \
	test_MOVLLG.bin \
	test_MOVBSG.bin \
	test_MOVWSG.bin \
	test_MOVLSG.bin \
	test_MOVBS4.bin \
	test_MOVWS4.bin \
	test_MOVLS4.bin \
	test_MOVBL4.bin \
	test_MOVWL4.bin \
	test_MOVLL4.bin \
	test_MOVA.bin \
	# \
	

%.py: ../sh4eb/system/%.s
	python3 ../sh4eb/system/gen_test_py.py $(notdir $<) > $@

%.o: ../sh4eb/system/%.s
	sh-elf-gcc -c -Wa,-gstabs -o $@ $<

%.elf: %.o
	sh-elf-ld -T../sh4eb/system/sh7750r_boot.ld -nostartfiles -o $@ $<

%.bin: %.elf
	sh-elf-objcopy -j .text -j .data -O binary $< $@

define RUN_TEST
	$(eval binname := $1)
	$(eval pyname := $(patsubst %.bin,%.py,$1))
	@$(QEMU) -s -S -firmware $(binname) > /dev/null 2>&1 &
	@python3 $(pyname)

endef

.PHONY:check-tcg-sh-isa
check-tcg-sh-isa: $(BINARIES) $(patsubst %.bin,%.py,$(BINARIES))
	@touch shix_linux_nand.bin
	@cp ../sh4eb/system/auto_test2.py ./
	$(foreach binary, $(BINARIES) ,$(call RUN_TEST,$(binary)))

.PRECIOUS: %.o %.elf %.bin

.PHONY:clean
clean:
	rm -rf /qemu/tests/tcg/sh4eb-softmmu/*

EXTRA_RUNS+=check-tcg-sh-isa
