# -*- Mode: makefile -*-
#
# SuperH specific tweaks
#

.SUFFIXES:

BINARIES = test_MOVI.bin test_MOVWI.bin

%.py: ../sh4eb/system/%.s
	python3 ../sh4eb/system/gen_test_py.py $(notdir $<) > $@

%.o: ../sh4eb/system/%.s
	sh-elf-gcc -c -Wa,-gstabs -o $@ $<

%.elf: %.o
	sh-elf-ld -T../sh4eb/system/sh7750r_boot.ld -nostartfiles -o $@ $<

%.bin: %.elf
	sh-elf-objcopy -j .text -j .data -O binary $< $@

define RUN_TEST
	$(eval binname := $1)
	$(eval pyname := $(patsubst %.bin,%.py,$1))
	@$(QEMU) -s -S -firmware $(binname) > /dev/null 2>&1 &
	@python3 $(pyname)

endef

.PHONY:check-tcg-sh-isa
check-tcg-sh-isa: $(BINARIES) $(patsubst %.bin,%.py,$(BINARIES))
	@touch shix_linux_nand.bin
	@cp ../sh4eb/system/auto_test2.py ./
	$(foreach binary, $(BINARIES) ,$(call RUN_TEST,$(binary)))

.PRECIOUS: %.o %.elf %.bin

.PHONY:clean
clean:
	rm -rf /qemu/tests/tcg/sh4eb-softmmu/*

EXTRA_RUNS+=check-tcg-sh-isa
